name: "golan_db"

services:
  database:
    restart: always
    container_name: go-mysql
    networks:
      - local
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pwsd-go
      MYSQL_DATABASE: golan_api
      MYSQL_USER: guser
      MYSQL_PASSWORD: pwsd-go

networks:
  local:
